# Generated by Django 5.2.7 on 2025-12-03 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('game_mode', models.CharField(choices=[('single', 'Single Player'), ('multi', 'Two Players'), ('ai_vs_p1', 'Player vs AI')], default='single', max_length=20)),
                ('player_one_name', models.CharField(max_length=150)),
                ('player_two_name', models.CharField(blank=True, help_text='Leave empty if there is no Player 2', max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True if game is still in progress')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('total_time_seconds', models.PositiveIntegerField(blank=True, help_text='Total time from start to finish, in seconds', null=True)),
                ('progress_percent', models.FloatField(default=0, help_text='Rough percent of maze completed (0–100).')),
                ('current_room', models.CharField(blank=True, help_text="e.g., 'Room 3' or coordinates", max_length=100, null=True)),
                ('current_door', models.PositiveIntegerField(blank=True, help_text='Door index the player is currently near', null=True)),
                ('current_leader', models.CharField(choices=[('player_one', 'Player One'), ('player_two', 'Player Two'), ('ai', 'AI'), ('tie', 'Tie / Equal'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('player_one_score', models.IntegerField(default=0)),
                ('player_two_score', models.IntegerField(default=0)),
                ('ai_score', models.IntegerField(default=0)),
                ('player_one_door_failures', models.PositiveIntegerField(default=0)),
                ('player_two_door_failures', models.PositiveIntegerField(default=0)),
                ('ai_failures', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('puzzles_solved', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0, help_text="Number of times a player 'died'/failed hard.")),
                ('winner', models.CharField(choices=[('player_one', 'Player One'), ('player_two', 'Player Two'), ('ai', 'AI'), ('none', 'No Winner / Incomplete')], default='none', max_length=20)),
                ('game_mode_detail', models.CharField(blank=True, help_text="Optional: e.g. 'Player1 vs AI (hard)'", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('events_log', models.JSONField(blank=True, help_text='Optional JSON of moves, doors, etc.', null=True)),
                ('created_at_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
