# Generated by Django 5.2.3 on 2025-12-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze_app', '0002_gamelog_player_delete_player1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='gameID',
        ),
        migrations.RemoveField(
            model_name='player',
            name='playerID',
        ),
    ]
