# Generated by Django 5.2.3 on 2025-12-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_app', '0003_remove_gamelog_gameid_remove_player_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answer_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='answer_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
