# Generated by Django 5.2.3 on 2025-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_app', '0004_alter_player_answer_right_alter_player_answer_wrong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='player1_name',
        ),
        migrations.AddField(
            model_name='player',
            name='player2_name',
            field=models.CharField(default='Player1', max_length=255),
            preserve_default=False,
        ),
    ]
