# Generated by Django 5.2.3 on 2025-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_app', '0005_rename_player_name_player_player1_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameLog',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='answer_right',
            new_name='player1_answer_right',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='answer_wrong',
            new_name='player1_answer_wrong',
        ),
        migrations.AddField(
            model_name='player',
            name='player2_answer_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player2_answer_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
